apiVersion: v2
name: testchart
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.19"

dependencies:
  - name: nginx
    version: "11.1.5"
    repository: https://charts.bitnami.com/bitnami
